# Fly.io app configuration for the Go/Baduk WebSocket server
# Replace "go-baduk-yourname" with your desired unique app name before deploying
app = "go-baduk-abetv"
primary_region = "cdg" # set to your closest region, e.g., ewr, iad, lax, cdg, sin, syd

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 100

  # Optional basic health check
  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"

